### ISSUE TITLE
I cannot install the torchlars library which is said to be inconsistent with others installed as required.

### ISSUE THREAD

**Issue by Anyway2022** [silvia1993/HyMOS#3]
Does anyone have the same problem?

**Comment by silvia1993** [comment]
Do you try to install torchlars as the last one?

**Comment by Anyway2022** [comment]
Other libraries are installed without problems. Only Torchlars cannot be installed.
So, Am I supposed to install Torchlars as the first one? or the last one?

**Comment by Anyway2022** [comment]
Almost same error here：https://github.com/kakaobrain/torchlars/issues/10

**Comment by silvia1993** [comment]
You should install Torchlars as the last one.

**Comment by Anyway2022** [comment]
Unfortunately, I tried but failed at last. Now that Lars facilitates a large batch size, Is it appropriate that I use sgd instead?

**Comment by FrancescoCappio** [comment]
LARS is implemented as a wrapper around SGD, so you could try removing it and use directly SGD. We never tried training HyMOS without LARS, in principle it should work, even if we cannot guarantee that it would obtain the exact same results

**Comment by Anyway2022** [comment]
Thank you~ Actually, I tried to use SGD directly but failed to reproduce the results. But the good news is that I succeeded in installing torchlars lib on another server with different OS and GPUs. Now, I can reproduce these results in the paper. Fantastic research work！
