### ISSUE TITLE
Why not use self-supervised contrastive loss which is already implemented in your codes？

### ISSUE THREAD

**Issue by Anyway2022** [silvia1993/HyMOS#7]
Hi, I am wondering, since the self-supervised contrastive loss was implemented in the file contrastive_loss.py, why is it not used in the end? Is there any reason? Wouldn't it be better if self-supervised contrastive loss and the supervised version are used together? Looking forward to your reply, thanks!

**Comment by FrancescoCappio** [comment]
The supervised and self-supervised contrastive loss may have different and contrasting objectives. 

The objective of HyMOS training is to learn a structured feature space in which the surface of an hypersphere hosts compact and well separated class clusters. We obtain this result using the supervised contrastive loss which pushes all samples of the same class to come together, regardless of their domain. 

On the contrary the self supervised contrastive loss can be seen as an instance classification loss: in practice it treats each training sample as belonging to a different class and tries to separate those classes. This means that with a self supervised contrastive loss two different samples of the same semantic class represent two different instances and are pushed far away. 

As a result by using the supervised contrastive loss and the self supervised one together the two objectives would be opposing: the supervised loss would push two different samples of the same class towards each other, while the self supervised one would push them far away.

**Comment by Anyway2022** [comment]
Thank you for your explanation！
